stages:
  - frontend-test
  - frontend-build
frontend-test:
  image: node:16.6-alpine
  stage: frontend-test
  needs: []
  script:
    - yarn install --network-timeout 10000000
    - yarn test:ci

frontend-build:
  image: docker:stable
  stage: frontend-build
  needs: [frontend-test]
  only:
    - staging
    - master
  dependencies:
    - frontend-test
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} $CI_REGISTRY
    - docker build -t $CI_REGISTRY/root/personnal-website/frontend:latest .
    - docker push $CI_REGISTRY/eurovox/root/personnal-website/frontend:latest